apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: vivekguptalandmarkgroupin/kafka:consumer-image-latest
          env:
            - name: spring.cloud.stream.kafka.binder.brokers
              value: 'kafka-service:9092'
            - name: spring.cloud.stream.kafka.binder.defaultBroker
              value: 'kafka-service:9092'
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"   # Even smaller memory request
              cpu: "100m"       # Even smaller CPU request
            limits:
              memory: "256Mi"  # Limit memory to 128 MiB
              cpu: "200m"      # Limit CPU to 100m (0.1 core)
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
