apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: vivekguptalandmarkgroupin/kafka:consumer-image-latest
        ports:
        - containerPort: 8080   # Exposing port 8080 for the consumer container
        resources:
          limits:
            memory: "256Mi" # Maximum memory the container can use
            cpu: "500m"     # Maximum CPU the container can use (50% of a single core)
          requests:
            memory: "128Mi" # Minimum memory requested
            cpu: "250m"     # Minimum CPU requested

---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
