apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: default  # Ensure this is the namespace where you want to deploy the Ingress resource
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Ensures requests are rewritten to root
spec:
  ingressClassName: nginx  # Specifies which ingress controller should handle this ingress
  rules:
    - host: practice.kafka  # The hostname to match for incoming requests
      http:
        paths:
          - path: /kafdrop
            pathType: Prefix  # Match paths starting with /kafdrop
            backend:
              service:
                name: kafdrop
                port:
                  number: 9000

          - path: /
            pathType: Prefix  # Default path for the Kafdrop service
            backend:
              service:
                name: kafdrop
                port:
                  number: 9000

          - path: /producer/  # Path for accessing the producer service
            pathType: Prefix  # Matches paths starting with /producer
            backend:
              service:
                name: producer-service  # Ensure the producer-service is running in the 'default' namespace
                port:
                  number: 80  # The port where the producer-service is exposed