  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kafka-config
  data:
    KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
    KAFKA_LISTENER_PORT: "9092"
    KAFKA_ADVERTISED_LISTENER: "PLAINTEXT://kafka-0.kafka-headless.default.svc.cluster.local:9092"
    KAFKA_LISTENER_NAME: PLAINTEXT
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
