apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: 3
  serviceName: kafka-headless
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.2.1
          command:
            - "/bin/bash"
            - "-c"
            - |
              # Set POD_NAME and KAFKA_BROKER_ID
              export POD_NAME=$(hostname)
              export KAFKA_BROKER_ID=$(echo $POD_NAME | grep -oP '\d+')
              # Set the advertised listener to use the correct DNS name for each broker
              export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://$POD_NAME.kafka-headless.default.svc.cluster.local:9092"
              # Run Kafka with the set broker ID
              exec /etc/confluent/docker/run
          envFrom:
            - configMapRef:
                name: kafka-config
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: LoadBalancer  # Expose Kafka to the outside world using a LoadBalancer
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka
