server:
  port: 9991
spring:
  cloud:
    stream:
      bindings:
        backpressur:
          binder: kafka
          destination: backpressure
      kafka:
        binder:
          brokers: kafka-service:9099
