server:
  port: 9992
spring:
  cloud:
    stream:
      function:
        definition: backpressureInput # Links to the functional bean name
      bindings:
        backpressureInput-in-0: # Binding name for the input topic
          destination: backpressure # Explicitly bind to the 'backpressure' topic
          group: backpressure-consumer # Consumer group for Kafka
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMaxInterval: 10000
      kafka:
        binder:
          brokers: kafka-service:9002
          autoCreateTopics: false       # Prevent auto-creation of topics by Kafka binder
          requiredAcks: 1               # Acknowledgment level for message reliability
          configuration:
            max.poll.records: 500       # Limits batch size to manage load
            enable.auto.commit: false   # Ensures manual commit (for reliable processing)
logging:
  level:
    org:
      apache:
        kafka: DEBUG
      springframework:
        cloud:
          stream: DEBUG  # Enables detailed logging for stream bindings
