server:
  port: 9991

spring:
  cloud:
    stream:
      bindings:
        backpressureOutput:
          destination: backpressure
      kafka:
        binder:
          brokers: kafka-service:9092
          autoCreateTopics: false       # Prevent auto-creation of topics by Kafka binder
          requiredAcks: 1               # Acknowledgment level for message reliability
          configuration:
            max.poll.records: 500       # Limits batch size to manage load
            enable.auto.commit: false   # Ensures manual commit (for reliable processing)

logging:
  level:
    org:
      springframework:
        cloud:
          stream: DEBUG  # Enables detailed logging for stream bindings
